import type { Metadata } from 'next'
import './globals.css'
import { DotGothic16 } from 'next/font/google'
import { cn } from '@/utils/css'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const pixelFont = DotGothic16({
    weight: ['400'],
    subsets: ['latin'],
})

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <body>
                <header className='w-full border-b-2 border-black border-dashed'>
                    <div className='container m-auto py-6'>
                        <h1
                            className={cn(
                                'text-lg font-medium',
                                pixelFont.className,
                            )}
                        >
                            Package Size
                        </h1>
                    </div>
                </header>
                <main>{children}</main>
            </body>
        </html>
    )
}
