import type { Metadata } from 'next'
import './globals.css'
import { cn, contentFont } from '@/utils/css'
import { PropsWithChildren } from 'react'
import { SiGithub } from '@icons-pack/react-simple-icons'
import blogpostIcon from '@/assets/blog-post.svg'
import Image from 'next/image'
import Link from 'next/link'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: PropsWithChildren) {
    return (
        <html lang='en' className='h-full'>
            <body className={cn(contentFont.className, 'flex h-full flex-col')}>
                <header className='basis-32 border-b border-black'>
                    <div className='container m-auto flex h-full w-full items-center justify-between border-x border-black px-12'>
                        <Link href={'/'}>
                            <h1 className='text-2xl'>Package size</h1>
                        </Link>
                        <div>
                            <SiGithub size={32} />
                        </div>
                    </div>
                </header>
                <main className='h-full overflow-scroll'>
                    <div className='container m-auto h-full w-full border-x border-black p-12'>
                        {children}
                    </div>
                </main>
                <footer className='basis-32 border-t border-black'>
                    <div className='container m-auto flex h-full w-full items-center justify-between border-x border-black px-12'>
                        <Image
                            src={blogpostIcon}
                            alt='Blog post icon'
                            width={40}
                            height={40}
                        />
                        <div className='flex flex-col text-lg'>
                            <p>AkaraChen</p>
                            <p className='ml-auto'>
                                {new Date().getFullYear()}
                            </p>
                        </div>
                    </div>
                </footer>
            </body>
        </html>
    )
}
